const constants = {

    ADD_ASSISTANT: "ADD_ASSISTANT",
    ADD_ASSISTANT_ADDRESS: "ADD_ASSISTANT_ADDRESS",
    ADD_ASSISTANT_PHONE: "ADD_ASSISTANT_PHONE",
    ADD_ASSISTANT_EMAIL: "ADD_ASSISTANT_EMAIL",

    EDIT_ASSISTANT: "EDIT_ASSISTANT",
    EDIT_ASSISTANT_NAME: "EDIT_ASSISTANT_NAME",
    EDIT_ASSISTANT_ADDRESS: "EDIT_ASSISTANT_ADDRESS",
    EDIT_ASSISTANT_PHONE: "EDIT_ASSISTANT_PHONE",
    EDIT_ASSISTANT_EMAIL: "EDIT_ASSISTANT_EMAIL",  
    
    REMOVE_ASSISTANT: "REMOVE_ASSISTANT"

}
export default constants